
const WALL_WIDTH = 20;
const MIN_RADIUS = 10;
const MAX_RADIUS = 110;
const MIN_SCALE = .1;
const MAX_SCALE = 1.5;
const TARGET_FREE_AREA_FRACTION = 0.3;
const SIGN = [1, -1];
const MAX_VELOCITY = .5;
const POSITIVE_SHADOW_COLOR = '14D414';
const NEGATIVE_SHADOW_COLOR = 'D40707';
const REFRESH_INTERVAL = 1000 * 60;